retcommercepricing-cosmosdb:
  type: cosmosdb
  deploymentParams:
    DBName: 'commercepricing'
    DBTier: 'Standard'
    Databases: 
      - Name: commercepricing
        RUPolicy: Autoscale
        SharedRU: 15000
        Collections:
            # Transactions
          - Name: commercepricingtransactions
            IndexingMode: Consistent # Consistent (synchronous, immediate consistency)
            ExcludedPaths:
              - '/*'
            PartitionKey: '/payload/id' 
            DefaultTtl: 1209600 
            # Master
          - Name: commercepricingmaster
            IndexingMode: Consistent # Consistent (synchronous, immediate consistency)
            ExcludedPaths:
              - '/*'
            PartitionKey: '/id'
            DefaultTtl: 1209600 
          - Name: leases
            IndexingMode: Consistent # Consistent (synchronous, immediate consistency) or Lazy (asynchronous, eventual consistency)
            PartitionKey: '/id' # required
resourceGroup:
  name: commerce-pricing-service
  location: westus3
  tags:
    application: commercepricingservice
    enterprise-resource: 'Yes'
    forecast-category: 'PnA'
    cost-center: 1002530100 
    managed-by: '#DTC_TechTeam@columbia.com'
    squad-Id: 10101 